# prefixキーをC-aに変更する
set -g prefix C-a

# デフォルトのprefixキーC-bを解除する
unbind C-b

# true color設定
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",alacritty:RGB"

# prefix+\でペインを垂直分割する
bind | split-window -h

# prefix+-でペインを水平分割する
bind - split-window -v

# ペインの移動
bind -n C-o select-pane -t :.+

# ペインを最大化
bind -n C-z resize-pane -Z

# ペインをリサイズする
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# ウィンドウを切り替える
bind -n S-left previous-window
bind -n S-right next-window

# windowのインデックスを1から始める
set -g base-index 1

# マウス操作を有効にする
set-option -g mouse on

# prefix+r で設定のリロード
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# tmux上でのコピー設定
set -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe-ands-cancel "pbcopy"

# List of plugins
set -g @plugin 'erikw/tmux-powerline'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# tpmの初期化（tmux.confの下の方に記述する）
run '~/.tmux/plugins/tpm/tpm'
